//  autogenerated  embed_dir  on ...


macro_rules! gen_get_includes_bytes{
    ($rel_path:expr, $($file:expr),+) => {
        pub fn get(file_name: &str) -> Option<&'static [u8]> {
            match file_name {
                $(
                    $file => Some(include_bytes!(concat!($rel_path, $file))),
                )+
                _ => None,
            }
        }
    }
}


gen_get_includes_bytes!("../../http_static/",
          "vendor.b9fe42a3611cccdfb0f3.bundle.js",
          "index.html",
          "main.eb1926c2d19bf72a13cf.bundle.js",
          "3rdpartylicenses.txt",
          "styles.1d8d1a57c0ce5744a7f0.bundle.css",
          "polyfills.ab8304790a25edec7f7d.bundle.js",
          "inline.8adf9c86f32c8fe1e422.bundle.js",
          "doc.png"
);
