[package]
name = "server_rust"
version = "0.1.0"
authors = ["maiquel <jleahred@gmail.com>"]

[dependencies]
iron ="*"
staticfile = "*"
mount = "*"

# [dependencies.iron]
# version = "*"

# [dependencies.mount]
# git = "https://github.com/iron/mount.git"