[package]
name = "dwd"
version = "0.1.0"
authors = ["maiquel <jleahred@gmail.com>"]

[dependencies]
iron ="*"
staticfile = "*"
mount = "*"
ws = "*"
serde = "1.0.10"
serde_json = "1.0"
serde_derive = "1.0.10"